# Generated by Django 4.2 on 2024-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_remove_user_role_user_created_user_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
